# Config reference:
# https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      major-updates:
        applies-to: version-updates
        update-types:
          - major
      minor-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
