const AVOID_SPACE_DELETION = ENV.VUE_APP_AVOID_SPACE_DELETION;
const IS_SPACE_DELETION_ENABLED = AVOID_SPACE_DELETION !== "true";

const SPACE_ROLE = Object.freeze({
  ADMIN: 100,
  USER: 50
});

export {
  IS_SPACE_DELETION_ENABLED,
  SPACE_ROLE
};
