const IS_SUBCRIPTION_ENABLED =
  process.env.VUE_APP_SUBSCRIPTION_ENABLED === "true";
const FREE_PLAN_STORAGE = process.env.VUE_APP_FREE_PLAN_STORAGE;
const PRO_PLAN_ID = process.env.VUE_APP_PRO_PLAN_ID;
const PRO_PLAN_STORAGE = process.env.VUE_APP_PRO_PLAN_STORAGE;
const DATAPACK_PLAN_ID = process.env.VUE_APP_DATAPACK_PLAN_ID;

export {
  IS_SUBCRIPTION_ENABLED,
  FREE_PLAN_STORAGE,
  PRO_PLAN_ID,
  PRO_PLAN_STORAGE,
  DATAPACK_PLAN_ID
};
