const SUBSCRIPTION_ENABLED = process.env.VUE_APP_SUBSCRIPTION_ENABLED;
const PADDLE_SANDBOX = process.env.VUE_APP_PADDLE_SANDBOX;
const PADDLE_VENDOR_ID = process.env.VUE_APP_PADDLE_VENDOR_ID;
const PRO_PLAN_ID = process.env.VUE_APP_PRO_PLAN_ID;
const DATAPACK_PLAN_ID = process.env.VUE_APP_DATAPACK_PLAN_ID;
const FREE_PLAN_STORAGE = process.env.VUE_APP_FREE_PLAN_STORAGE;
const PRO_PLAN_STORAGE = process.env.VUE_APP_PRO_PLAN_STORAGE;

const IS_SUBSCRIPTION_ENABLED = SUBSCRIPTION_ENABLED === "true";
const IS_PADDLE_SANDBOX = PADDLE_SANDBOX === "true";

export {
  IS_SUBSCRIPTION_ENABLED,
  IS_PADDLE_SANDBOX,
  PADDLE_VENDOR_ID,
  PRO_PLAN_ID,
  DATAPACK_PLAN_ID,
  FREE_PLAN_STORAGE,
  PRO_PLAN_STORAGE
};
