name: Platform-next

on: 
  push:
    branches:
      - feature/payment

env:
  app: platform_dev

jobs:
  test:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Wait for npm package
        id: viewer-install
        if: github.event.client_payload.ref
        timeout-minutes: 2
        run: |
          while ! npm install @bimdata/viewer@${{ github.event.client_payload.viewer-version }} --save; do
            sleep 5
          done
          GITDIFF=$(git diff -- package-lock.json) && echo "::set-output name=gitdiff::$GITDIFF"
      - run: npm ci
      #- run: npm run test:e2e
      - name: Commit diff
        if: steps.viewer-install.outputs.gitdiff
        uses: EndBug/add-and-commit@v7
        with:
          add: "package-lock.json package.json"
          message: "chore: bump @bimdata/viewer@${{ github.event.client_payload.viewer-version }} from Github Actions [skip ci]"

  build-and-push:
    runs-on: self-hosted
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: etc/Dockerfile
          push: true
          pull: true
          tags: |
            docker-registry.bimdata.io/bimdata/${{ env.app }}:${{ github.sha }}
            docker-registry.bimdata.io/bimdata/${{ env.app }}:staging

  deploy:
    runs-on: self-hosted
    needs: build-and-push
    steps:
      - name: Login to BIMData Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker-registry.bimdata.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Deploy on staging
        uses: bimdata/actions/deployment@v1
        with:
          inventory: staging
          app: ${{ env.app }}
          vault-pass: ${{ secrets.ANSIBLE_VAULT_PASSWD }}
